### ISSUE TITLE
POST http://api.zinger.pw/platform/v1/auth/login net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by jayanthrbharadwaj** [zinger-framework/zinger-ui#19]
Hi @harshavardhan98

This issue is regarding ERR_NAME_NOT_RESOLVED when I try to login on http://platform.zinger.pw:4200/auth/login.
It is hitting an API endpoint - http://api.zinger.pw/platform/v1/auth/login and ERR_NAME_NOT_RESOLVED. How do I host this API backend? is it available in zinger-core? If so can you please point me to to the link for postman collection for these API endpoints?

**Comment by ddlogesh** [comment]
The backend for this project: https://github.com/zinger-framework/zinger-rails
The documentation for this project is not yet completed, but please follow these 2 steps to get your setup done:

1. Add the below line to your hosts file as you did [here](https://github.com/zinger-framework/zinger-ui#update-hosts).
```
127.0.0.1	api.zinger.pw
```
2. Navigate to rails project root directory & run `docker-compose up`. The application will be running in `api.zinger.pw:80`

**Comment by ddlogesh** [comment]
@jayanthrbharadwaj 
FYI Updated documentation for Zinger Rails project here.
https://github.com/zinger-framework/zinger-rails#readme
