### ISSUE TITLE
Login to platform or admin UI

### ISSUE THREAD

**Issue by James7777** [zinger-framework/zinger-ui#22]
hi there,
thank you for this wonderful software, I was playing with it and managed to get it running but I am having an issue login to either platform or admin.
How do I do this on the desktop UI, also the mobile apps are not working either, after mobile authentication, the otp is generated and authentication completes but cant go past authentication after the a successful otp authentication.
Please help, I would like to see how it works, how to add shops etc.
thank you.
Caleb

**Comment by ddlogesh** [comment]
@James7777 
Zinger UI is a web dashboard specialized for shop and platform admins to manage end-to-end core operations.

[Zinger Rails](https://github.com/zinger-framework/zinger-rails) is a backend application that exposes the APIs for this project. So, please follow the readme to setup and run the application in the background.

**Comment by James7777** [comment]
Hi,
Thanks for your reply.
Is this not active then?
https://github.com/zinger-framework/zinger-ui
https://github.com/zinger-framework/zinger-core?

I am interested in the partner, customer, admin app, the java and android kotlin versions.
I am looking to test the food delivery usecase but the rails app seems to be different, are they?
thank you again for this amazing initiative.
Caleb

**Comment by ddlogesh** [comment]
Yes, zinger-core won't be active anymore & will be replaced with zinger-rails in sometime later.

Android apps are being ported to zinger-rails backend by @shrikanth7698 at the moment.
